backend:
  name: github
  repo: anjangpangesu/anjangpangesu.github.io
  branch: main
  use_graphql: true
  pkce: true

media_folder: "public/images/uploads"
public_folder: "/SnazBlogspot/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blogs"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Published", name: "published", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown"}
